development:
  adapter: postgresql
  encoding: unicode
  database: rails_saas_dev
  username: rails_saas
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: rails_saas_test
  username: rails_saas
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: rails_saas
  username: rails_saas
  pool: 5

